export const help = {
    en: {
        "HelpGuideTitle": "Game Guide",

        "GMMindTitle": "The GM's Mind: Understanding Your Narrator",
        "GMMindFullDesc": "The game is run by an AI Game Master (GM). It's crucial to understand how the GM perceives the world, as it has no human memory. Its entire reality is reconstructed each turn from specific data.\n\n**Short-Term Memory (The Last 15 Messages):**\nThe GM only has direct access to the last 15 messages of your conversation history. This serves as its immediate, short-term context.\n\n**Long-Term Memory (The External Chronicle):**\nFor everything that happened before those 15 messages, the GM relies on its 'External Memory'. This is a structured log built from the outcomes of previous turns. It includes:\n- **Location History (`lastEventsDescription`):** A log of significant events that have occurred in each location.\n- **Quest Logs (`detailsLog`):** Your progress, clues, and updates for every quest.\n- **NPC Journals (`NPCJournals`):** The private thoughts and reactions of characters you've interacted with.\n\nThis means that for an event to become a persistent part of the world's memory, it must be officially recorded by the GM in these logs. Your actions create the history that future versions of the GM will read to understand the world.",

        "QuestionModeTitle": "Question Mode: Talking to the GM",
        "QuestionModeFullDesc": "By prefixing your message with '[Question]', you can pause the game and speak directly to the Game Master out-of-character. Game time will not advance. This is a powerful tool for two purposes:\n\n1.  **Clarification:** You can ask about game rules, the current state of your character or the world, or for a reminder of details you may have forgotten (e.g., 'What did the bartender tell me about the bandits?').\n\n2.  **Correction:** If you notice a factual error in the game state (e.g., 'My health wasn't updated after I drank a potion,' or 'You mentioned an NPC, but they're not in my log'), you can report it. The GM will verify the error and, if confirmed, issue a correction to the game state to bring it in line with what should have happened.",

        "CharacteristicChecksTitle": "Action Checks",
        "CharacteristicChecksFullDesc": "Many actions with a chance of failure are resolved with an Action Check. This is a contested roll between your character's skill and the task's difficulty. The outcome is not a simple pass/fail; the 'Difference' between the rolls determines the quality of your success or failure, leading to more nuanced and realistic results.",
        "CharacteristicChecksExampleTitle": "Example: Forcing a Door (Strength Check)",
        "CharacteristicChecksExampleScenario": "You try to force open a heavy, barred door.",
        "CharacteristicChecksExampleContent": "1.  **Your Roll:** `d20 + StatModificator`\n2.  **Difficulty Roll:** `d20 + ActionDifficultModificator`\n3.  **Result:** `Your Roll - Difficulty Roll = Difference`\n\n-   **StatModificator:** Your total bonus for the action, calculated from your Strength, level, gear, skills, and any temporary effects.\n-   **ActionDifficultModificator:** The task's total difficulty, calculated from the door's sturdiness, the location's danger level, and other situational factors.\n\n**Interpreting the Difference:**\n- **≥ 10:** Critical Success (Exceptional outcome with a bonus)\n- **5 to 9:** Full Success (You achieve your goal perfectly)\n- **0 to 4:** Partial Success (You succeed, but with a complication or drawback)\n- **-5 to -1:** Minor Failure (You fail, with a minor negative consequence)\n- **-10 to -6:** Serious Failure (You fail badly, worsening your situation)\n- **< -10:** Critical Failure (A catastrophic outcome with severe consequences)",

        "ProgressionTitle": "Character Progression",
        "ProgressionFullDesc": "Your character grows through both planned advancement and practical experience.\n\n1.  **Leveling Up:** Gaining experience (XP) from completing quests, winning battles, and making discoveries will increase your level. Each new level grants you **5 Attribute Points** to permanently increase your Standard Characteristics.\n\n2.  **Skill Through Practice:** When you succeed at an action check ('Full' or 'Critical' success), the characteristic used is 'trained'. The game will attempt to grant you a **+1 bonus** to that Standard Characteristic. This is limited by a **'Training Cap'** equal to `Your Level * 2`. If your characteristic is already at or above this cap, you will instead receive a scaling XP reward calculated as `max(25, round(XP_for_next_level * 0.05))`.\n\n3.  **Persistent Effort:** Success isn't the only path to growth. If you achieve a **'Partial Success'** on an action check three times in a row using the *same characteristic*, you will be awarded a **+1 bonus** to that Standard Characteristic as a reward for your perseverance.",

        "CombatTitle": "Combat",
        "CombatFullDesc": "Combat is turn-based and resolved in rounds. The flow of combat depends on your game mode.\n\n- **Standard Combat (Single Player):** The GM simulates the entire round at once. Initiative for all combatants is calculated, and turns are resolved in order from highest to lowest.\n\n- **Asynchronous Combat (Co-op 'Full Party' Mode):** Combat is resolved one character at a time. The GM will process the turns of any AI opponents that act before you, then resolve your turn, and then stop and wait for the next human player.\n\n**Core Mechanics:**\n1.  **Initiative:** At the start of combat, every participant's initiative is calculated based on their 'Speed' characteristic to determine turn order.\n\n2.  **Surprise:** If you successfully ambush an enemy (e.g., by attacking from stealth), you may get a 'surprise round' to act before normal initiative order begins.\n\n3.  **Your Turn:** You declare an action (e.g., attacking, casting a spell, using an item). The success of your action is determined by an Action Check.\n\n4.  **Damage & Defense:** Damage is calculated based on your weapon, skills, and characteristics. Critical hits deal significantly more damage. An opponent's armor and resistances can reduce or even completely negate incoming damage if it's below their 'Damage Threshold'.",

        "LocationDifficultyTitle": "Location Difficulty",
        "LocationDifficultyFullDesc": "Every location has two 'Difficulty Profiles' to represent how dangerous it is for different people:\n\n-   **External Profile:** This is the difficulty for 'Outsiders'—enemies, or you when you are in a hostile area. A high external combat difficulty means the location is well-defended against intruders.\n\n-   **Internal Profile:** This is the difficulty for 'Insiders'—the faction that controls the location and their allies. A location is usually much safer for its own inhabitants, so this profile's values are typically much lower.\n\nThe GM uses the appropriate profile to determine the difficulty of your actions. Each profile has four facets that apply to different actions:\n- **Combat:** Used for attack and combat skill checks.\n- **Environment:** Used for physical challenges like climbing, dodging traps, or resisting hazards.\n- **Social:** Used for persuasion, intimidation, and other social interactions.\n- **Exploration:** Used for searching for secrets, deciphering clues, and navigation.",

        "StealthAndDetectionTitle": "Stealth and Detection",
        "StealthAndDetectionFullDesc": "Stealth is an active contest, not simple invisibility.\n\n1.  **Entering Stealth:** You make a Dexterity check to become hidden. Success activates stealth mode and sets your 'Detection Level' to a low value.\n\n2.  **Detection Level (0-100):** This tracks how close you are to being discovered. Every action you take while stealthy (moving, picking a lock) increases this level. 0 is perfectly hidden, 100 is fully detected.\n\n3.  **NPC Detection:** As your detection level rises, NPCs may become suspicious and use their turn to make an active Perception check. The difficulty for their check (the 'Stealth DC') is calculated as `(Your Dexterity Modifier + Situational Bonuses) - (Your Detection Level / 2)`. This means the more mistakes you make, the easier you are to find.\n\n4.  **Generic Enemy Detection:** Less important enemies don't make active checks. Instead, at the end of your turn, they have a percentage chance to notice you equal to your current `Detection Level`.\n\n5.  **Benefits:** Attacking an unaware enemy from stealth grants a massive bonus ('Great Advantage') on your attack roll, often resulting in a critical hit.",

        "LootGenerationTitle": "Loot Generation",
        "LootGenerationFullDesc": "The quality and type of items you find are not entirely random. On most turns, the game system pre-generates a list of loot templates based on your performance and current situation. When you find an item, the GM uses one of these templates. If the list is empty, the GM can dynamically generate a new item from scratch.",
        "LootGenerationKeyFactorsTitle": "Key Factors for Future Loot",
        "LootGenerationKeyFactorsDesc": "Each turn, the following coefficients are calculated and sent to the system to influence the quality of loot generated for *future* turns:",
        "LootGenerationKeyFactorsL1": "**Item Search Coefficient:** Based on bonuses from your gear related to finding items.",
        "LootGenerationKeyFactorsL2": "**Location Coefficient:** Based on the overall difficulty and value of your current location. Dangerous dungeons yield better loot than peaceful villages.",
        "LootGenerationKeyFactorsL3": "**Danger Coefficient:** Reflects the immediate threat level. Being in active combat increases the potential for valuable rewards.",
        "LootGenerationKeyFactorsL4": "**Logic Coefficient:** How logical is it to find an item here? (e.g., finding a sword in a guardhouse is very logical).",
        "LootGenerationKeyFactorsL5": "**Characters Coefficient:** Reflects the social complexity. Interacting with important NPCs can lead to unique item rewards.",
        "LootGenerationPlayerInfluenceTitle": "Your Direct Influence on Current Loot",
        "LootGenerationPlayerInfluenceDesc": "Your stats and actions have a direct impact on the items you get *right now*:",
        "LootGenerationPlayerInfluenceL1": "**Action Success:** Achieving a 'Critical Success' on a search, crafting, or quest action that rewards an item can significantly improve its quality and properties, upgrading it beyond the base template.",
        "LootGenerationPlayerInfluenceL2": "**Defeating Named NPCs:** Looting a named character will prioritize the actual gear they were using, ensuring consistency.",
        "LootGenerationProcessTitle": "The Process",
        "LootGenerationProcessDesc": "In short:",
        "LootGenerationProcessL1": "You perform an action to find loot (search a chest, defeat an enemy).",
        "LootGenerationProcessL2": "The GM takes a template from a pre-generated list or, if the list is empty, dynamically creates a new item based on the situation and the Key Factors.",
        "LootGenerationProcessL3": "The success of your action (e.g., a 'Critical Success' on the search) can upgrade the item you receive.",
        "LootGenerationFinalResultTitle": "The Final Result",
        "LootGenerationFinalResultDesc": "This system means that challenging dangerous, high-value locations and skillfully performing your actions is the best way to find legendary treasures.",

        "KeyFormulasTitle": "Key Formulas",
        "KeyFormulasDesc": "This section contains the core mathematical formulas the GM uses to run the game. Understanding these can help you optimize your character builds and strategies.",

        "KeyFormulasPrimaryStatsTitle": "Primary Stats",
        "KeyFormulasPrimaryStatsDesc": "These are the foundational stats derived from your Standard Characteristics.",
        "KeyFormulasPrimaryStatsContent": "**Max Health:**\n`100 + floor(StdConstitution * 2.0) + floor(StdStrength * 1.0)`\n\n**Max Energy:**\n`100 + floor(StdConstitution * 0.75) + floor(StdIntelligence * 0.75) + floor(StdWisdom * 0.75) + floor(StdFaith * 0.75)`\n\n**Max Weight (kg):**\n`30 + floor(StdStrength * 1.8 + StdConstitution * 0.4)`",

        "KeyFormulasCombatStatsTitle": "Combat Stats",
        "KeyFormulasCombatStatsDesc": "These stats determine your effectiveness in combat and are derived from your Level and Modified Characteristics.",
        "KeyFormulasCombatStatsContent": "**Level Attack Bonus:**\n`5 + floor(Level / 10) * 2`\n\n**Characteristic Attack Bonus:**\n`floor(ModifiedRelevantCharacteristic / 2.5)`\n\n**Level Resistance:**\n`floor(Level / 10) * 2`\n\n**Constitution Resistance Bonus:**\n`floor(ModifiedConstitution / 10)`\n\n**Crit Threshold (d20 roll needed):**\n`20 - floor(StandardLuck / 20)`\n\n**Crit Damage Multiplier:**\n`1.5 + (floor(ModifiedLuck / 2) / 100)`",

        "KeyFormulasActionChecksTitle": "Action Checks",
        "KeyFormulasActionChecksDesc": "This formula determines your 'StatModificator', which is your total bonus for an action check.",
        "KeyFormulasActionChecksContent": "**1. StatValueWithBonuses:**\n`(StandardStat + FlatBonuses) * PercentMultiplier`\n\n**2. CappedStatValue:**\n`min((Level * 0.5 + 20), StatValueWithBonuses)`\n\n**3. LevelScaling:**\n`floor(Level * 0.8)`\n\n**4. Final StatModificator:**\n`CappedStatValue + LevelScaling`",

        "KeyFormulasSkillScalingTitle": "Skill Scaling",
        "KeyFormulasSkillScalingDesc": "This formula determines how much a skill's power increases based on your stats.",
        "KeyFormulasSkillScalingContent": "**1. CharBonus%:**\n`floor(RelevantCharValue / 10) * 5`\n\n**2. LevelBonus%:**\n`floor(Level / 5) * 8`\n\n**3. MasteryBonus%:**\n`floor(MasteryLevel / 1) * 4`\n\n**4. TotalBonusMultiplier:**\n`1 + (CharBonus % + LevelBonus % + MasteryBonus %) / 100`\n\n**5. Final Effect Value:**\n`round(BaseValue * TotalBonusMultiplier)`",

        "KeyFormulasLevelUpTitle": "Level Progression",
        "KeyFormulasLevelUpDesc": "The amount of experience needed to advance from your current level (L) to the next is calculated with the following formula.",
        "KeyFormulasLevelUpContent": "**XP for next level (from L to L+1):**\n```\nXP_Needed(L) = floor(100 * (L ^ 2.5)) \n```",

        "KeyFormulasXPTitle": "Experience Rewards",
        "KeyFormulasXPDesc": "The formula for calculating XP rewards is complex, ensuring rewards are balanced and meaningful. For difficult tasks, it scales with the XP needed for your next level. For trivial tasks (where the task level is more than 10 levels below you), it uses a simpler formula to provide a small, flat reward.",
        "KeyFormulasXPContent": "**For Relevant Tasks:**\n**1. Base Calculation:**\n`BaseXP = TotalXPForLevel * BaseRewardPercentage * LevelDepthCoefficient`\n\n**2. Final XP:**\n`experienceGained = floor(BaseXP * All_Situational_Multipliers)`\n\n- **TotalXPForLevel:** The total XP needed for your current level.\n- **BaseRewardPercentage (BRP):** A percentage based on the task's significance (e.g., 10% for a standard combat, 30% for a major quest objective).\n- **LevelDepthCoefficient:** A scaling factor that makes higher levels require more effort.\n- **Situational Multipliers:** A series of multipliers that reward difficulty, creativity, first-time achievements, and exploiting enemy weaknesses.\n\n**For Trivial Tasks:**\n`experienceGained = (PlayerLevel * 5) + (TaskLevel * 10)`"
    },
    ru: {
        "HelpGuideTitle": "Справка по игре",

        "GMMindTitle": "Разум Мастера Игры: Понимание вашего рассказчика",
        "GMMindFullDesc": "Игру ведет Мастер Игры (ИИ). Важно понимать, как он воспринимает мир, поскольку у него нет человеческой памяти. Вся его реальность воссоздается на каждом ходу из конкретных данных.\n\n**Краткосрочная память (Последние 15 сообщений):**\nМастер Игры имеет прямой доступ только к последним 15 сообщениям вашей истории переписки. Это служит его непосредственным, краткосрочным контекстом.\n\n**Долгосрочная память (Внешняя Хроника):**\nДля всего, что произошло до этих 15 сообщений, Мастер Игры полагается на свою «Внешнюю Память». Это структурированный журнал, построенный на результатах предыдущих ходов. Он включает:\n- **История Локаций (`lastEventsDescription`):** Журнал значимых событий, произошедших в каждой локации.\n- **Журналы Квестов (`detailsLog`):** Ваш прогресс, подсказки и обновления по каждому квесту.\n- **Дневники NPC (`NPCJournals`):** Личные мысли и реакции персонажей, с которыми вы взаимодействовали.\n\nЭто означает, что для того, чтобы событие стало постоянной частью мировой памяти, оно должно быть официально записано Мастером в этих журналах. Ваши действия создают историю, которую будущие «версии» Мастера будут читать, чтобы понять мир.",

        "QuestionModeTitle": "Режим Вопроса: Разговор с Мастером Игры",
        "QuestionModeFullDesc": "Добавив в начало сообщения '[Question]', вы можете приостановить игру и обратиться напрямую к Мастеру Игры вне роли. Игровое время не будет продвигаться. Это мощный инструмент для двух целей:\n\n1.  **Прояснение:** Вы можете спрашивать о правилах игры, текущем состоянии вашего персонажа или мира, или просить напомнить детали, которые вы могли забыть (например, 'Что трактирщик рассказал мне о бандитах?').\n\n2.  **Исправление:** Если вы заметили фактическую ошибку в состоянии игры (например, 'Мое здоровье не обновилось после того, как я выпил зелье', или 'Вы упомянули NPC, но его нет в моем журнале'), вы можете сообщить об этом. Мастер проверит ошибку и, если она подтвердится, внесет исправление в состояние игры, чтобы привести его в соответствие с тем, что должно было произойти.",

        "CharacteristicChecksTitle": "Проверки Действий",
        "CharacteristicChecksFullDesc": "Многие действия с шансом провала разрешаются с помощью Проверки Действия. Это встречный бросок между навыком вашего персонажа и сложностью задачи. Результат — это не просто успех/провал; «Разница» между бросками определяет качество вашего успеха или неудачи, что приводит к более тонким и реалистичным результатам.",
        "CharacteristicChecksExampleTitle": "Пример: Выламывание двери (Проверка Силы)",
        "CharacteristicChecksExampleScenario": "Вы пытаетесь выломать тяжелую, запертую на засов дверь.",
        "CharacteristicChecksExampleContent": "1.  **Ваш бросок:** `d20 + StatModificator`\n2.  **Бросок сложности:** `d20 + ActionDifficultModificator`\n3.  **Результат:** `Ваш бросок - Бросок сложности = Разница`\n\n-   **StatModificator:** Ваш общий бонус для действия, рассчитанный из вашей Силы, уровня, снаряжения, навыков и любых временных эффектов.\n-   **ActionDifficultModificator:** Общая сложность задачи, рассчитанная из прочности двери, уровня опасности локации и других ситуационных факторов.\n\n**Интерпретация Разницы:**\n- **≥ 10:** Критический Успех (Исключительный результат с бонусом)\n- **5 до 9:** Полный Успех (Вы идеально достигаете своей цели)\n- **0 до 4:** Частичный Успех (Вы преуспеваете, но с осложнением или недостатком)\n- **-5 до -1:** Незначительная Неудача (Вы терпите неудачу с незначительным негативным последствием)\n- **-10 до -6:** Серьезная Неудача (Вы крупно проваливаетесь, ухудшая свое положение)\n- **< -10:** Критическая Неудача (Катастрофический исход с серьезными последствиями)",

        "ProgressionTitle": "Прогрессия Персонажа",
        "ProgressionFullDesc": "Ваш персонаж развивается как через плановое продвижение, так и через практический опыт.\n\n1.  **Повышение уровня:** Получение опыта (XP) за выполнение квестов, победы в боях и совершение открытий повысит ваш уровень. Каждый новый уровень дает вам **5 очков атрибутов** для постоянного увеличения ваших Стандартных Характеристик.\n\n2.  **Навык через практику:** Когда вы успешно проходите проверку действия («Полный» или «Критический» успех), характеристика, использованная для этой проверки, «тренируется». Игра попытается дать вам **бонус +1** к этой Стандартной Характеристике. Это ограничено **«Тренировочным пределом»**, равным `Ваш Уровень * 2`. Если ваша характеристика уже достигла этого предела или превышает его, вы получите вместо этого масштабированную награду в виде XP, рассчитанную как `max(25, round(XP_для_след_уровня * 0.05))`.\n\n3.  **Постоянное Усилие:** Успех — не единственный путь к росту. Если вы достигнете **«Частичного Успеха»** в проверке действия три раза подряд, используя *одну и ту же характеристику*, вы получите **бонус +1** к этой Стандартной Характеристике в награду за ваше упорство.",

        "CombatTitle": "Бой",
        "CombatFullDesc": "Бой пошаговый и проходит в раундах. Механика боя зависит от вашего игрового режима.\n\n- **Стандартный Бой (Одиночная игра):** Мастер Игры симулирует весь раунд сразу. Рассчитывается инициатива для всех участников, и ходы разрешаются в порядке от наивысшей к наинизшей.\n\n- **Асинхронный Бой (Кооперативный режим 'Full Party'):** Бой разрешается по одному персонажу за раз. Мастер обработает ходы всех ИИ-противников, которые действуют до вас, затем разрешит ваш ход, после чего остановится и будет ждать следующего игрока.\n\n**Основные Механики:**\n1.  **Инициатива:** В начале боя для каждого участника рассчитывается инициатива на основе его характеристики «Скорость» для определения порядка ходов.\n\n2.  **Внезапность:** Если вы успешно устроите засаду на врага (например, атаковав из скрытности), вы можете получить «раунд внезапности», чтобы действовать до начала обычного порядка инициативы.\n\n3.  **Ваш ход:** Вы объявляете действие (например, атака, заклинание, использование предмета). Успех вашего действия определяется Проверкой Действия.\n\n4.  **Урон и Защита:** Урон рассчитывается на основе вашего оружия, навыков и характеристик. Критические удары наносят значительно больше урона. Броня и сопротивления противника могут уменьшить или даже полностью свести на нет входящий урон, если он ниже их «Порога Урона».",

        "LocationDifficultyTitle": "Сложность Локации",
        "LocationDifficultyFullDesc": "У каждой локации есть два «Профиля сложности», чтобы показать, насколько она опасна для разных людей:\n\n-   **Внешний профиль:** Это сложность для «Чужаков» — врагов или вас, когда вы находитесь на враждебной территории. Высокая внешняя боевая сложность означает, что локация хорошо защищена от незваных гостей.\n\n-   **Внутренний профиль:** Это сложность для «Своих» — фракции, контролирующей локацию, и их союзников. Локация обычно намного безопаснее для своих обитателей, поэтому значения этого профиля обычно намного ниже.\n\nМастер использует соответствующий профиль для определения сложности ваших действий. У каждого профиля есть четыре аспекта, которые применяются к разным действиям:\n- **Бой:** Используется для проверок атак и боевых навыков.\n- **Окружение:** Используется для физических испытаний, таких как лазание, уклонение от ловушек или сопротивление опасностям.\n- **Социум:** Используется для убеждения, запугивания и других социальных взаимодействий.\n- **Исследование:** Используется для поиска секретов, расшифровки подсказок и навигации.",

        "StealthAndDetectionTitle": "Скрытность и Обнаружение",
        "StealthAndDetectionFullDesc": "Скрытность — это активное соревнование, а не простая невидимость.\n\n1.  **Вход в скрытность:** Вы должны сделать проверку Ловкости, чтобы спрятаться. Успех активирует режим скрытности и устанавливает ваш «Уровень обнаружения» на низкое значение.\n\n2.  **Уровень обнаружения (0-100):** Этот показатель отслеживает, насколько вы близки к обнаружению. Каждое ваше действие в скрытности (движение, взлом замка) увеличивает этот уровень. 0 — вы полностью скрыты, 100 — вас обнаружили.\n\n3.  **Обнаружение NPC:** По мере роста вашего уровня обнаружения, NPC могут стать подозрительными и использовать свой ход для активной проверки Восприятия. Сложность их проверки («Сложность Скрытности») рассчитывается как `(Ваш Модификатор Ловкости + Ситуационные Бонусы) - (Ваш Уровень Обнаружения / 2)`. Это означает, что чем больше ошибок вы совершаете, тем легче вас найти.\n\n4.  **Обнаружение Обычными Врагами:** Менее важные враги не делают активных проверок. Вместо этого, в конце вашего хода, у них есть процентный шанс заметить вас, равный вашему текущему `Уровню Обнаружения`.\n\n5.  **Преимущества:** Атака на не подозревающего врага из скрытности дает огромное преимущество («Великое Преимущество») при броске на атаку, что часто приводит к критическому удару.",

        "LootGenerationTitle": "Генерация Добычи",
        "LootGenerationFullDesc": "Качество и тип находимых вами предметов не совсем случайны. На большинстве ходов система игры предварительно генерирует список шаблонов добычи на основе вашей производительности и текущей ситуации. Когда вы находите предмет, Мастер Игры использует один из этих шаблонов. Если список пуст, Мастер может динамически сгенерировать новый предмет с нуля.",
        "LootGenerationKeyFactorsTitle": "Ключевые факторы для будущей добычи",
        "LootGenerationKeyFactorsDesc": "Каждый ход рассчитываются следующие коэффициенты и отправляются в систему, чтобы повлиять на качество добычи, генерируемой для *будущих* ходов:",
        "LootGenerationKeyFactorsL1": "**Коэффициент поиска предметов:** Зависит от бонусов вашего снаряжения, связанных с поиском предметов.",
        "LootGenerationKeyFactorsL2": "**Коэффициент локации:** Зависит от общей сложности и ценности вашей текущей локации. Опасные подземелья приносят лучшую добычу, чем мирные деревни.",
        "LootGenerationKeyFactorsL3": "**Коэффициент опасности:** Отражает текущий уровень угрозы. Нахождение в активном бою увеличивает потенциал для ценных наград.",
        "LootGenerationKeyFactorsL4": "**Коэффициент логики:** Насколько логично найти предмет здесь? (например, найти меч в казарме очень логично).",
        "LootGenerationKeyFactorsL5": "**Коэффициент персонажей:** Отражает социальную сложность. Взаимодействие с важными NPC может привести к уникальным наградам в виде предметов.",
        "LootGenerationPlayerInfluenceTitle": "Ваше прямое влияние на текущую добычу",
        "LootGenerationPlayerInfluenceDesc": "Ваши характеристики и действия оказывают прямое влияние на предметы, которые вы получаете *прямо сейчас*:",
        "LootGenerationPlayerInfluenceL1": "**Успех действия:** Достижение «Критического Успеха» при проверке поиска, создания предмета или квеста, который вознаграждает предметом, может значительно улучшить его качество и свойства, превзойдя базовый шаблон.",
        "LootGenerationPlayerInfluenceL2": "**Добыча с Именных NPC:** Добыча с побежденного именного персонажа будет в первую очередь состоять из его реального снаряжения, обеспечивая последовательность мира.",
        "LootGenerationProcessTitle": "Процесс",
        "LootGenerationProcessDesc": "Вкратце:",
        "LootGenerationProcessL1": "Вы совершаете действие для получения добычи (обыскиваете сундук, побеждаете врага).",
        "LootGenerationProcessL2": "Мастер берет шаблон из предварительно сгенерированного списка или, если список пуст, динамически создает новый предмет на основе ситуации и Ключевых Факторов.",
        "LootGenerationProcessL3": "Успех вашего действия (например, «Критический Успех» при поиске) может улучшить получаемый вами предмет.",
        "LootGenerationFinalResultTitle": "Конечный результат",
        "LootGenerationFinalResultDesc": "Эта система означает, что бросать вызов опасным, ценным локациям с хорошо экипированным и умелым персонажем — лучший способ найти легендарные сокровища.",

        "KeyFormulasTitle": "Ключевые формулы",
        "KeyFormulasDesc": "Этот раздел содержит основные математические формулы, которые использует Мастер Игры. Их понимание может помочь вам оптимизировать развитие вашего персонажа и стратегии.",

        "KeyFormulasPrimaryStatsTitle": "Основные параметры",
        "KeyFormulasPrimaryStatsDesc": "Это базовые параметры, производные от ваших Стандартных Характеристик.",
        "KeyFormulasPrimaryStatsContent": "**Макс. Здоровье:**\n`100 + floor(СтдТелосложение * 2.0) + floor(СтдСила * 1.0)`\n\n**Макс. Энергия:**\n`100 + floor(СтдТелосложение * 0.75) + floor(СтдИнтеллект * 0.75) + floor(СтдМудрость * 0.75) + floor(СтдВера * 0.75)`\n\n**Макс. Вес (кг):**\n`30 + floor(СтдСила * 1.8 + СтдТелосложение * 0.4)`",

        "KeyFormulasCombatStatsTitle": "Боевые параметры",
        "KeyFormulasCombatStatsDesc": "Эти параметры определяют вашу эффективность в бою и зависят от вашего Уровня и Модифицированных Характеристик.",
        "KeyFormulasCombatStatsContent": "**Бонус атаки от уровня:**\n`5 + floor(Уровень / 10) * 2`\n\n**Бонус атаки от характеристики:**\n`floor(Модиф.РелевантнаяХарактеристика / 2.5)`\n\n**Сопротивление от уровня:**\n`floor(Уровень / 10) * 2`\n\n**Бонус сопротивления от телосложения:**\n`floor(Модиф.Телосложение / 10)`\n\n**Порог крит. удара (нужный бросок d20):**\n`20 - floor(СтандартнаяУдача / 20)`\n\n**Множитель крит. урона:**\n`1.5 + (floor(Модиф.Удача / 2) / 100)`",

        "KeyFormulasActionChecksTitle": "Проверки действий",
        "KeyFormulasActionChecksDesc": "Эта формула определяет ваш 'StatModificator', который является вашим общим бонусом для проверки действия.",
        "KeyFormulasActionChecksContent": "**1. StatValueWithBonuses:**\n`(СтандартнаяХарактеристика + ФиксированныеБонусы) * ПроцентныйМножитель`\n\n**2. CappedStatValue:**\n`min((Уровень * 0.5 + 20), StatValueWithBonuses)`\n\n**3. LevelScaling:**\n`floor(Уровень * 0.8)`\n\n**4. Итоговый StatModificator:**\n`CappedStatValue + LevelScaling`",

        "KeyFormulasSkillScalingTitle": "Масштабирование навыков",
        "KeyFormulasSkillScalingDesc": "Эта формула определяет, насколько увеличивается сила навыка в зависимости от ваших характеристик.",
        "KeyFormulasSkillScalingContent": "**1. CharBonus%:**\n`floor(РелевантнаяХарактеристика / 10) * 5`\n\n**2. LevelBonus%:**\n`floor(Уровень / 5) * 8`\n\n**3. MasteryBonus%:**\n`floor(УровеньМастерства / 1) * 4`\n\n**4. TotalBonusMultiplier:**\n`1 + (CharBonus % + LevelBonus % + MasteryBonus %) / 100`\n\n**5. Итоговое значение эффекта:**\n`round(БазовоеЗначение * TotalBonusMultiplier)`",

        "KeyFormulasLevelUpTitle": "Прогрессия уровня",
        "KeyFormulasLevelUpDesc": "Количество опыта, необходимое для перехода с вашего текущего уровня (L) на следующий, рассчитывается по следующей формуле.",
        "KeyFormulasLevelUpContent": "**Опыта для следующего уровня (с L на L+1):**\n```\nXP_Needed(L) = floor(100 * (L ^ 2.5)) \n```",

        "KeyFormulasXPTitle": "Награды за опыт",
        "KeyFormulasXPDesc": "Формула для расчета наград за опыт сложна, что обеспечивает сбалансированные и значимые награды. Для сложных задач она масштабируется в зависимости от опыта, необходимого для вашего следующего уровня. Для тривиальных задач (где уровень задачи более чем на 10 уровней ниже вашего), используется более простая формула для предоставления небольшой, фиксированной награды.",
        "KeyFormulasXPContent": "**Для Релевантных Задач:**\n**1. Базовый расчет:**\n`BaseXP = TotalXPForLevel * BaseRewardPercentage * LevelDepthCoefficient`\n\n**2. Итоговый опыт:**\n`experienceGained = floor(BaseXP * Все_Ситуационные_Множители)`\n\n- **TotalXPForLevel:** Общее количество опыта, необходимое для вашего текущего уровня.\n- **BaseRewardPercentage (BRP):** Процент, основанный на значимости задачи (например, 10% за стандартный бой, 30% за цель основного квеста).\n- **LevelDepthCoefficient:** Масштабирующий фактор, который делает более высокие уровни требующими больших усилий.\n- **Ситуационные Множители:** Ряд множителей, которые вознаграждают за сложность, креативность, первые достижения и использование уязвимостей врагов.\n\n**Для Тривиальных Задач:**\n`experienceGained = (УровеньИгрока * 5) + (УровеньЗадачи * 10)`"
    }
}