export const ancientLoc = {
    en: {
        'The Unfrozen': "The Unfrozen",
        "You are an echo from a forgotten age, a survivor of a world that exists only in myth. Awakening from a damaged cryo-pod after millennia of forced sleep, you are a living anachronism. Your mind holds fragmented memories of starships and psionic power, but your ancient knowledge clashes with the primitive reality of this new Earth. Your journey is one of rediscovery—piecing together your lost history while grappling with a future you were never meant to see. Bonus: +2 Intelligence, +1 Luck.": "You are an echo from a forgotten age, a survivor of a world that exists only in myth. Awakening from a damaged cryo-pod after millennia of forced sleep, you are a living anachronism. Your mind holds fragmented memories of starships and psionic power, but your ancient knowledge clashes with the primitive reality of this new Earth. Your journey is one of rediscovery—piecing together your lost history while grappling with a future you were never meant to see. Bonus: +2 Intelligence, +1 Luck.",
        'Psion': 'Psion',
        "You are one of the Awakened who has learned to consciously access the 'null-space'. To others, it looks like magic or miracles, but for you, it is the manipulation of unseen energies and probabilities, a power that strains the mind and draws unwanted attention. Bonus: +2 Wisdom, +1 Faith.": "You are one of the Awakened who has learned to consciously access the 'null-space'. To others, it looks like magic or miracles, but for you, it is the manipulation of unseen energies and probabilities, a power that strains the mind and draws unwanted attention. Bonus: +2 Wisdom, +1 Faith.",
        'Sorcerer': 'Sorcerer',
        "A wielder of hidden arcane energies, drawing power from forgotten rituals and ley lines that run beneath the concrete and steel of the modern world. Their magic is often subtle, influencing luck and perception. Bonus: +2 Wisdom, +1 Luck.": "A wielder of hidden arcane energies, drawing power from forgotten rituals and ley lines that run beneath the concrete and steel of the modern world. Their magic is often subtle, influencing luck and perception. Bonus: +2 Wisdom, +1 Luck.",
        'Truth-Seeker': 'Truth-Seeker',
        "A driven investigator, rogue academic, or obsessive blogger. You piece together forgotten history from fractured myths, strange artifacts, and genetic anomalies, determined to expose the truth of humanity's origins, no matter how dangerous. Bonus: +2 Perception, +1 Intelligence.": "A driven investigator, rogue academic, or obsessive blogger. You piece together forgotten history from fractured myths, strange artifacts, and genetic anomalies, determined to expose the truth of humanity's origins, no matter how dangerous. Bonus: +2 Perception, +1 Intelligence.",
    },
    ru: {
        'The Unfrozen': "Размороженный",
        "You are an echo from a forgotten age, a survivor of a world that exists only in myth. Awakening from a damaged cryo-pod after millennia of forced sleep, you are a living anachronism. Your mind holds fragmented memories of starships and psionic power, but your ancient knowledge clashes with the primitive reality of this new Earth. Your journey is one of rediscovery—piecing together your lost history while grappling with a future you were never meant to see. Bonus: +2 Intelligence, +1 Luck.": "Вы — эхо из забытой эпохи, выживший из мира, который существует только в мифах. Пробудившись из поврежденной криокапсулы после тысячелетий вынужденного сна, вы — живой анахронизм. Ваш разум хранит обрывочные воспоминания о звездолетах и псионической силе, но ваши древние знания вступают в противоречие с примитивной реальностью этой новой Земли. Ваш путь — это путь переоткрытия: собирая воедино свою утерянную историю и борясь с будущим, которое вы никогда не должны были увидеть. Бонус: +2 к Интеллекту, +1 к Удаче.",
        'Psion': 'Псион',
        "You are one of the Awakened who has learned to consciously access the 'null-space'. To others, it looks like magic or miracles, but for you, it is the manipulation of unseen energies and probabilities, a power that strains the mind and draws unwanted attention. Bonus: +2 Wisdom, +1 Faith.": "Вы один из Пробуждённых, научившийся сознательно входить в «нуль-пространство». Для других это выглядит как магия или чудеса, но для вас это манипуляция невидимыми энергиями и вероятностями — сила, которая напрягает разум и привлекает нежелательное внимание. Бонус: +2 к Мудрости, +1 к Вере.",
        'Sorcerer': 'Чародей',
        "A wielder of hidden arcane energies, drawing power from forgotten rituals and ley lines that run beneath the concrete and steel of the modern world. Their magic is often subtle, influencing luck and perception. Bonus: +2 Wisdom, +1 Luck.": "Владелец скрытых тайных энергий, черпающий силу из забытых ритуалов и лей-линий, проходящих под бетоном и сталью современного мира. Их магия часто тонка и влияет на удачу и восприятие. Бонус: +2 к Мудрости, +1 к Удаче.",
        'Truth-Seeker': 'Искатель Истины',
        "A driven investigator, rogue academic, or obsessive blogger. You piece together forgotten history from fractured myths, strange artifacts, and genetic anomalies, determined to expose the truth of humanity's origins, no matter how dangerous. Bonus: +2 Perception, +1 Intelligence.": "Целеустремлённый следователь, неортодоксальный учёный или одержимый блогер. Вы собираете воедино забытую историю из обрывков мифов, странных артефактов и генетических аномалий, твёрдо решив раскрыть правду о происхождении человечества, какой бы опасной она ни была. Бонус: +2 к Восприятию, +1 к Интеллекту.",
    }
};