
export const characteristics = {
  en: {
    // Characteristics
    'strength': 'Strength',
    'dexterity': 'Dexterity',
    'constitution': 'Constitution',
    'intelligence': 'Intelligence',
    'wisdom': 'Wisdom',
    'faith': 'Faith',
    'attractiveness': 'Attractiveness',
    'trade': 'Trade',
    'persuasion': 'Persuasion',
    'perception': 'Perception',
    'luck': 'Luck',
    'speed': 'Speed',

    // Characteristic Descriptions
    'characteristic_description_strength': `Represents a character's raw physical power, muscular development, and their ability to exert brute force. It governs how much they can lift, carry, push, pull, and how hard they can hit with sheer might. Used for: lifting heavy portcullises, breaking down doors, attacks with strength-based weapons (e.g., a greataxe), climbing, intimidation, and resisting physical force.\n\n**Mechanically affects:**\n- Maximum carry weight (MaxWeight)\n- Maximum health (MaxHealth)\n- Damage from strength-based attacks.`,
    'characteristic_description_dexterity': `Represents a character's fine motor control, precision, balance, and complex physical coordination. It dictates their ability to perform delicate tasks, aim accurately, and execute movements that require technical skill and grace. Used for: aiming ranged weapons, evasive maneuvers, attacks requiring technique (e.g., with a rapier), moving silently, picking locks, acrobatics, and sleight of hand.\n\n**Mechanically affects:**\n- Damage from attacks requiring precision (e.g., ranged weapons, finesse attacks).`,
    'characteristic_description_constitution': `Represents a character's health, physical resilience, stamina, and ability to withstand pain, disease, and environmental hardships. It's a measure of their bodily fortitude. Primarily used for: resisting poisons and diseases, enduring extreme weather, holding one's breath, and undertaking prolonged strenuous activity.\n\n**Mechanically affects:**\n- Maximum health (MaxHealth)\n- Maximum energy (MaxEnergy)\n- Maximum carry weight (MaxWeight)\n- Resistance to all damage types.`,
    'characteristic_description_intelligence': `Represents a character's capacity for logical reasoning, memory, analytical thought, knowledge acquisition and recall, and complex problem-solving. It is the measure of their intellect and deductive capabilities. Used for: deciphering codes, recalling information, understanding mechanisms, investigation, identifying magical items, formulating tactics, crafting items, and casting knowledge-based magic.\n\n**Mechanically affects:**\n- Maximum energy (MaxEnergy)\n- Damage from spells and abilities based on intelligence.`,
    'characteristic_description_wisdom': `Represents a character's intuition, willpower, common sense, situational awareness, empathy, and practical judgment. It's about insight, understanding of motivations, and connection to the world. Used for: noticing hidden details, detecting lies, resisting mental manipulation, making sound judgments, applying practical skills (e.g., herbalism), and casting intuitive magic (druidic, shamanistic).\n\n**Mechanically affects:**\n- Maximum energy (MaxEnergy)\n- Effectiveness of abilities based on intuition and willpower.`,
    'characteristic_description_faith': `Represents the strength and depth of a character's belief system, their conviction in a higher power, cause, or personal philosophy, and their spiritual resolve or connection to the divine/supernatural. Used for: channeling divine magic (healing, protection), performing sacred rites, resisting effects that target the soul, and inspiring allies through conviction.\n\n**Mechanically affects:**\n- Maximum energy (MaxEnergy)\n- Power of divine spells and abilities.`,
    'characteristic_description_attractiveness': `Represents a character's physical beauty, charisma stemming from appearance, and their ability to make a strong, often positive, initial visual impression. Used for: seduction, charming, gaining initial attention, and flirting to distract or disarm. Its effectiveness is highly dependent on the target's personality, mood, and priorities.`,
    'characteristic_description_trade': `Represents a character's acumen in commerce, their skill in negotiating prices, appraising the value of goods, and understanding market dynamics. Used specifically for: haggling with merchants, appraising the value of treasures, and identifying counterfeits.\n\n**Mechanically affects:**\n- Outcomes of checks related to trading and item appraisal.`,
    'characteristic_description_persuasion': `Represents the ability to influence others through reasoned argument, diplomacy, rhetoric, eloquent speech, bluffing, or appealing to their logic, emotions, or self-interest. Used for: convincing officials, debating, calming tense situations, delivering inspiring speeches, and bluffing to bypass checks.\n\n**Mechanically affects:**\n- Outcomes of checks related to persuasion, diplomacy, and deception.`,
    'characteristic_description_perception': `Represents a character's ability to notice details and stimuli in their environment using all their senses (sight, hearing, smell, taste, touch) and to interpret those sensory inputs. Used for: searching for hidden objects, spotting ambushes, eavesdropping, identifying unusual smells, and following tracks.\n\n**Mechanically affects:**\n- Outcomes of checks related to searching, detection, and attentiveness.`,
    'characteristic_description_luck': `Represents innate fortune, serendipity, and a character's propensity for improbable outcomes, both good and bad. It's the unquantifiable element of chance. Used for: passively influencing critical hit chance, checks in games of chance, random guesses, and "hail Mary" actions where other characteristics are insufficient.\n\n**Mechanically affects:**\n- Critical hit chance\n- Additional critical hit damage.\n\n### Standard Luck and Critical Hits\n\nStandard Luck directly influences your character's ability to land critical hits in combat. The higher your Standard Luck, the lower the number you need to roll on a 20-sided die to score a critical hit.\n\n| Standard Luck | Crit Threshold | Crit Chance (d20) | Required Roll |\n|:-------------:|:--------------:|:-----------------:|:-----------------------------:|\n| 0 - 19        | 20             | 5%                | Only 20       |\n| 20 - 39       | 19             | 10%               | 19 or 20      |\n| 40 - 59       | 18             | 15%               | 18, 19, 20    |\n| 60 - 79       | 17             | 20%               | 17, 18, 19, 20|\n| 80 - 99       | 16             | 25%               | 16, 17, 18, 19, 20         |\n| 100           | 15             | 30%               | 15, 16, 17, 18, 19, 20             |\n\n### Modified Luck and "Lucky Strikes" in Looting\n\nModified Luck (including bonuses from gear and effects) significantly impacts the quality of items you find. It gives you a chance for a "Lucky Strike," which can upgrade a found item's quality or add extra bonuses.\n\n| Modified Luck | "Lucky Strike" Chance | Description |\n|:-------------:|:---------------------:|:------------|\n| 10            | 5%                    | A small but pleasant chance to improve an item. |\n| 30            | 15%                   | A noticeable chance to get something special. |\n| 50            | 25%                   | Every fourth item could potentially be improved. |\n| 70            | 35%                   | A very high chance, significantly affecting loot quality. |\n| 100           | 50%                   | A huge chance! Every second item could be improved. |`,
    'characteristic_description_speed': `Represents a character's raw velocity, reaction time, and frequency of action. It governs how fast a character can move, react to sudden events, and overwhelm with rapid, simple strikes. Primarily used for: calculating initiative in combat and maximum movement distance in a tactical situation or chase.\n\n**Mechanically affects:**\n- Initiative in combat (turn order)\n- Movement distance.`,
  },
  ru: {
    // Characteristics
    'strength': 'Сила',
    'dexterity': 'Ловкость',
    'constitution': 'Телосложение',
    'intelligence': 'Интеллект',
    'wisdom': 'Мудрость',
    'faith': 'Вера',
    'attractiveness': 'Привлекательность',
    'trade': 'Торговля',
    'persuasion': 'Убеждение',
    'perception': 'Восприятие',
    'luck': 'Удача',
    'speed': 'Скорость',

    // Characteristic Descriptions
    'characteristic_description_strength': `Отражает грубую физическую силу персонажа, развитие мускулатуры и способность применять грубую силу. Определяет, сколько персонаж может поднять, перенести, толкнуть, потянуть и насколько сильно ударить. Используется для: подъема тяжелых решеток, выламывания дверей, атак силовым оружием (например, секирой), лазания, запугивания и сопротивления физическому воздействию.\n\n**Механически влияет на:**\n- Максимальный переносимый вес (MaxWeight)\n- Максимальное здоровье (MaxHealth)\n- Урон от атак, основанных на силе.`,
    'characteristic_description_dexterity': `Отражает мелкую моторику, точность, равновесие и сложную физическую координацию. Определяет способность выполнять деликатные задачи, точно целиться и выполнять движения, требующие технического мастерства и изящества. Используется для: прицеливания из дальнобойного оружия, уклонений, атак, требующих техники (например, рапирой), бесшумного передвижения, взлома замков, акробатики и ловкости рук.\n\n**Механически влияет на:**\n- Урон от атак, требующих точности (например, стрелковое оружие, финты).`,
    'characteristic_description_constitution': `Отражает здоровье, физическую стойкость, выносливость и способность противостоять боли, болезням и тяготам окружающей среды. Это мера телесной крепости. В основном используется для: сопротивления ядам и болезням, перенесения экстремальных погодных условий, задержки дыхания и выполнения длительных изнурительных действий.\n\n**Механически влияет на:**\n- Максимальное здоровье (MaxHealth)\n- Максимальную энергию (MaxEnergy)\n- Максимальный переносимый вес (MaxWeight)\n- Сопротивление всем видам урона.`,
    'characteristic_description_intelligence': `Отражает способность к логическому мышлению, память, аналитические способности, получение и воспроизведение знаний, а также решение сложных задач. Это мера интеллекта и дедуктивных способностей. Используется для: расшифровки кодов, вспоминания информации, понимания механизмов, расследования, определения магических предметов, разработки тактики, создания предметов и применения магии, основанной на знаниях.\n\n**Механически влияет на:**\n- Максимальную энергию (MaxEnergy)\n- Урон от заклинаний и способностей, основанных на интеллекте.`,
    'characteristic_description_wisdom': `Отражает интуицию, силу воли, здравый смысл, ситуационную осведомленность, эмпатию и практическое суждение. Это проницательность, понимание мотивов и связь с миром. Используется для: замечания скрытых деталей, распознавания лжи, сопротивления ментальному воздействию, принятия взвешенных решений, применения практических навыков (например, травничества) и использования интуитивной магии (друидической, шаманской).\n\n**Механически влияет на:**\n- Максимальную энергию (MaxEnergy)\n- Эффективность способностей, основанных на интуиции и воле.`,
    'characteristic_description_faith': `Отражает силу и глубину системы верований персонажа, его убежденность в высшей силе, деле или личной философии, а также его духовную решимость или связь с божественным/сверхъестественным. Используется для: применения божественной магии (исцеление, защита), выполнения священных обрядов, сопротивления эффектам, нацеленным на душу, и вдохновения союзников силой убеждения.\n\n**Механически влияет на:**\n- Максимальную энергию (MaxEnergy)\n- Силу божественных заклинаний и способностей.`,
    'characteristic_description_attractiveness': `Отражает физическую красоту, харизму, исходящую от внешности, и способность производить сильное, часто положительное, первое визуальное впечатление. Используется для: соблазнения, очаровывания, привлечения первоначального внимания и флирта с целью отвлечь или обезоружить. Эффективность сильно зависит от личности, настроения и приоритетов цели.`,
    'characteristic_description_trade': `Отражает коммерческую хватку, умение договариваться о ценах, оценивать стоимость товаров и понимать динамику рынка. Используется специально для: торга с купцами, оценки стоимости сокровищ и определения подделок.\n\n**Механически влияет на:**\n- Результаты проверок, связанных с торговлей и оценкой предметов.`,
    'characteristic_description_persuasion': `Отражает способность влиять на других с помощью аргументации, дипломатии, риторики, красноречия, блефа или обращения к их логике, эмоциям или личным интересам. Используется для: убеждения чиновников, ведения дебатов, успокоения напряженных ситуаций, произнесения вдохновляющих речей и блефа для прохождения проверок.\n\n**Механически влияет на:**\n- Результаты проверок, связанных с убеждением, дипломатией и обманом.`,
    'characteristic_description_perception': `Отражает способность замечать детали и стимулы в окружающей среде, используя все органы чувств (зрение, слух, обоняние, вкус, осязание) и интерпретировать эти сенсорные данные. Используется для: поиска скрытых рычагов, обнаружения засад, подслушивания разговоров, определения необычных запахов и следования по следам.\n\n**Механически влияет на:**\n- Результаты проверок, связанных с поиском, обнаружением и внимательностью.`,
    'characteristic_description_luck': `Отражает врожденную удачу, счастливые случайности и склонность персонажа к маловероятным исходам, как хорошим, так и плохим. Это неизмеримый элемент случайности. Используется для: пассивного влияния на шанс критического удара, проверок в азартных играх, совершенно случайных догадок и попыток «последней надежды», когда другие характеристики и навыки недостаточны.\n\n**Механически влияет на:**\n- Шанс критического удара\n- Дополнительный урон от критического удара.\n\n### Стандартная Удача и Критические Удары\n\nСтандартная Удача напрямую влияет на способность вашего персонажа наносить критические удары в бою. Чем выше ваша Стандартная Удача, тем меньшее число вам нужно выбросить на 20-гранном кубике, чтобы нанести критический удар.\n\n| Вложено очков в Стандартную Удачу | Порог критического удара | Шанс на крит (на d20) | Необходимый бросок |\n|:--------------------------------:|:-------------------------:|:---------------------:|:------------------:|\n| 0 - 19                           | 20                        | 5%                    | Только 20          |\n| 20 - 39                          | 19                        | 10%                   | 19 или 20         |\n| 40 - 59                          | 18                        | 15%                   | 18, 19, 20        |\n| 60 - 79                          | 17                        | 20%                   | 17, 18, 19, 20    |\n| 80 - 99                          | 16                        | 25%                   | 16, 17, 18, 19, 20             |\n| 100                              | 15                        | 30%                   | 15, 16, 17, 18, 19, 20             |\n\n### Модифицированная Удача и \"Удар Удачи\" при поиске добычи\n\nМодифицированная Удача (включая бонусы от снаряжения и эффектов) значительно влияет на качество находимых вами предметов. Она дает шанс на \"Удар Удачи\", который может улучшить качество найденного предмета или добавить ему дополнительные бонусы.\n\n| Модифицированная Удача | Шанс \"Удара Удачи\" | Описание |\n|:----------------------:|:------------------:|:---------|\n| 10                     | 5%                 | Небольшой, но приятный шанс на улучшение предмета. |\n| 30                     | 15%                | Заметный шанс получить что-то особенное. |\n| 50                     | 25%                | Каждый четвертый предмет потенциально может быть улучшен. |\n| 70                     | 35%                | Очень высокий шанс, значительно влияющий на качество добычи. |\n| 100                    | 50%                | Огромный шанс! Каждый второй предмет может получить улучшение. |`,
    'characteristic_description_speed': `Отражает чистую скорость, время реакции и частоту действий. Определяет, как быстро персонаж может перемещаться, реагировать на внезапные события и ошеломлять быстрыми, простыми ударами. В основном используется для: расчета инициативы в бою и максимальной дистанции передвижения в тактической ситуации или погоне.\n\n**Механически влияет на:**\n- Инициативу в бою (порядок хода)\n- Дистанцию передвижения.`,
  }
};