
export const help = {
  en: {
    // Help Guide
    "HelpGuideTitle": "Game Guide",
    "CharacteristicChecksTitle": "Characteristic Checks",
    "CharacteristicChecksFullDesc": "Every action you take whose outcome is uncertain requires a **Characteristic Check**. This is the core mechanic that determines how successfully you accomplish a task, whether it's picking a lock, persuading a guard, or attacking an enemy.\n\nWhenever you perform such an action, the following process happens behind the scenes:\n\n* **1. Characteristic Association:** The Game Master (AI) determines which of your characteristics (Strength, Dexterity, Intelligence, etc.) is key to this action.\n* **2. Dice Roll (d20):** The system rolls a 20-sided die. The result can be influenced by **Advantage** or **Disadvantage**, which are divided into two levels:\n    *   **Normal Advantage/Disadvantage:** Two 20-sided dice are rolled, and the **best** (for Advantage) or **worst** (for Disadvantage) result is used for the check.\n    *   **Great Advantage / Dire Disadvantage:** Three 20-sided dice are rolled, and the **best** (for Advantage) or **worst** (for Disadvantage) result of the three is used.\n\n    These conditions are applied based on the circumstances (e.g., attacking from an ambush provides Advantage, while shooting in the dark imposes Disadvantage).\n* **3. Modifier Calculation:** Your **Statistic Modifier** (calculated from your characteristic and level) is added to your roll, while a **Difficulty Modifier** (dependent on task complexity, the situation, and the Game Master's dice roll) opposes it.\n* **4. Determining the Outcome:** The final difference between your result and the difficulty determines the degree of success. There are six levels of outcome:\n    *   **Critical Success:** You achieve your goal brilliantly, exceeding all expectations. You not only succeed but also gain an additional bonus or create an unexpected advantage.\n    *   **Full Success:** You completely achieve your intended goal without any negative consequences.\n    *   **Partial Success:** You achieve your main goal, but at a cost: complications arise, the result is incomplete, or there are unforeseen side effects.\n    *   **Minor Failure:** You do not achieve your goal. The consequences are minimal—perhaps you wasted time or ended up in a slightly disadvantageous position.\n    *   **Serious Failure:** You fail, and the situation noticeably worsens. You might take damage, lose an item, or give the enemy a significant advantage.\n    *   **Critical Failure:** A catastrophic failure. The worst plausible scenario occurs, with severe and possibly long-term consequences.",

    "Critical Success": "Critical Success",
    "Full Success": "Full Success",
    "Partial Success": "Partial Success",
    "Minor Failure": "Minor Failure",
    "Serious Failure": "Serious Failure",
    "Critical Failure": "Critical Failure",

    "CharacteristicChecksExampleTitle": "Detailed Example: Persuading a Guard",
    "CharacteristicChecksExampleScenario": "You are trying to persuade a stern-looking guard to let you through the city gates after curfew. It's risky, and the guard looks incorruptible.",
    "CharacteristicChecksExampleContent": "**1. Characteristic Association:** The Game Master determines that **Persuasion** is the key characteristic for convincing the guard.\n\n**2. Advantage/Disadvantage:** You have no clear advantages, but trying this at night is suspicious. The Game Master decides you have **Normal Disadvantage**.\n\n**3. Dice Roll:** Due to Disadvantage, the system rolls two d20s and takes the lower result. Let's say the rolls are **16** and **7**. The value used for the check is **7**.\n\n**4. Modifier Calculation:**\n*   **Your Statistic Modifier:** Calculated from your Persuasion characteristic (40) and level (10). Let's say the final modifier is **+32**.\n*   **Difficulty Modifier:** Calculated from the task's difficulty (incorruptible guard), the situation (night), and the Game Master's dice roll. Let's say the AI's roll was **12**, and the final difficulty modifier is **+25**.\n\n**5. Final Difference and Result:**\n*   **Your Total:** 7 (roll) + 32 (modifier) = **39**\n*   **Difficulty Total:** 12 (AI roll) + 25 (modifier) = **37**\n*   **Difference:** 39 - 37 = **+2**\n*   **Result:** A difference of +2 falls into the 0 to 5 range. This is a **Partial Success**.\n\n**Conclusion:** You didn't fully convince the guard, but he didn't raise the alarm. He says, \"I can't let you through the main gate, but if you hurry, you might slip through the old breach in the wall to the east. And don't let me see you again.\" You achieved your goal (getting into the city), but with a complication (using an unsafe path and drawing attention to yourself).",
    
    "CombatTitle": "Combat",
    "CombatFullDesc": "Combat is a structured process that occurs in **rounds**. In each round, all participants take their turn in the order of **Initiative**, which is determined by your **Speed** characteristic.\n\nKey Concepts:\n\n* **1. Percentage Points vs. Percentages:** This is important! Health and damage are measured in **Percentage Points (%)**—this is an absolute value (a powerful boss might have '500%' health). Resistances are measured in regular **Percentages (%)** and are used to calculate damage reduction.\n* **2. Actions on Your Turn:** On your turn, you can perform one **Main Action** (attack, use a skill) and **Movement**.\n* **3. Attack and Damage:** Your attack is a **Characteristic Check**. If successful, you deal damage that is subtracted from the target's health. The damage depends on your weapon, skills, and characteristics.\n* **4. Wounds:** Taking significant damage (more than 25% of max health in one hit) can result in **Wounds**—serious injuries that apply persistent debuffs until they are healed with special items or rest.\n* **5. Effects:** Many skills and attacks apply temporary effects:\n    *   **Buffs:** Positive effects that increase your stats or damage.\n    *   **Debuffs:** Negative effects that decrease an enemy's stats.\n    *   **Damage Over Time (DoT):** Damage dealt each turn (poison, burning).\n    *   **Control:** Effects that limit a target's actions (stun, immobility).",
    
    "StealthAndDetectionTitle": "Stealth and Detection",
    "StealthAndDetectionFullDesc": "Stealth is an active state that allows you to avoid enemies and gain a tactical advantage. It's not just invisibility, but a constant contest between your stealthiness and your opponents' vigilance.\n\n* **1. Entering Stealth:** To become stealthy, you must declare your intent (e.g., \"I try to sneak\"). The Game Master will determine if it's possible in the current environment. If so, you will make a **Dexterity** check. Success means you've entered stealth mode.\n* **2. Detection Level:** Your stealthiness is measured by a **Detection Level** (from 0 to 100). 0 means you are completely hidden. 100 means you have been detected. The higher the level, the more suspicion you arouse.\n* **3. Actions in Stealth:** Any action you take (moving, picking a lock, opening a door) increases your Detection Level. Noisy actions, like running in heavy armor or talking loudly, will immediately break your stealth.\n* **4. Detection:** Enemies can spot you. If your Detection Level becomes high enough, they will start actively searching for you, making **Perception** checks against your stealth. Their success can either further increase your detection level or fully reveal you.\n* **5. Advantages of Stealth:** Attacking an unaware enemy from stealth grants you **Great Advantage** on your attack roll, significantly increasing your chances of a critical hit. The attack itself breaks your stealth.",
    
    "LootGenerationTitle": "Loot Generation",
    "LootGenerationFullDesc": "The item creation system in the game is more than just random chance. It's a complex process that considers your character, their gear, and the current situation to create unique and appropriate rewards. The process has two stages: first, the system generates a **Loot Template**—a kind of \"recipe\"—and then the Game Master (AI) turns that template into a full-fledged item with a name and a story.",
    "LootGenerationKeyFactorsTitle": "Key Factors (Coefficients)",
    "LootGenerationKeyFactorsDesc": "At the end of each of your turns, the Game Master evaluates the situation based on five key coefficients. These coefficients directly influence the quality of loot in the next turn:",
    "LootGenerationKeyFactorsL1": "**Item Search Coefficient:** How much your current gear helps in finding treasures.",
    "LootGenerationKeyFactorsL2": "**Location Coefficient:** How rich or dangerous the current location is.",
    "LootGenerationKeyFactorsL3": "**Danger Coefficient:** How tense the current situation is. More danger means higher rewards.",
    "LootGenerationKeyFactorsL4": "**Logic Coefficient:** How logical it is to find something valuable right here, right now.",
    "LootGenerationKeyFactorsL5": "**Characters Coefficient:** Takes into account the complexity of social interaction (has a minor impact).",
    "LootGenerationPlayerInfluenceTitle": "Your Influence",
    "LootGenerationPlayerInfluenceDesc": "Besides external factors, your character is the main catalyst for good loot:",
    "LootGenerationPlayerInfluenceL1": "**Luck:** Perhaps the most important characteristic for finding treasures. It significantly boosts the overall quality of loot and gives a chance for a **\"Lucky Strike\"**—a special event that can upgrade an item's quality by a full tier or add an extra bonus to it!",
    "LootGenerationPlayerInfluenceL2": "**Level:** The higher your level, the greater the potential for finding higher-quality items.",
    "LootGenerationProcessTitle": "Template Generation Process",
    "LootGenerationProcessDesc": "For each potential item, the system goes through the following stages:",
    "LootGenerationProcessL1": "**1. Will anything be found?** There's always a chance of finding nothing, but your multipliers and luck can minimize it.",
    "LootGenerationProcessL2": "**2. Determining Quality:** The system makes a \"roll\" to determine the item's quality (from Unique to Trash). Your multipliers, level, and luck shift the probabilities in your favor, increasing the chances of getting rare items.",
    "LootGenerationProcessL3": "**3. Generating Bonuses:** The item's quality determines how many bonuses it will receive. High-quality items have a much higher chance of getting a **\"special\" bonus**—a unique effect, a curse, or a powerful conditional enhancement, rather than just a stat boost.",
    "LootGenerationFinalResultTitle": "The Final Result",
    "LootGenerationFinalResultDesc": "The result of this process is a **Loot Template** that is passed to the Game Master. This is why two swords with the same name can have completely different properties—they were created from different templates, generated under circumstances unique to you.",

    "KeyFormulasTitle": "Key Formulas",
    "KeyFormulasDesc": "Understanding these formulas will help you make more informed decisions in character development and combat.",
    "KeyFormulasPrimaryStatsTitle": "Primary Parameters",
    "KeyFormulasPrimaryStatsDesc": "These parameters are calculated based on your **standard** (base) characteristics and determine your survivability and stamina. Bonuses from gear do not affect them.",
    "KeyFormulasPrimaryStatsContent": "**Max Health (%)**\n```\n100 + floor(Std. Constitution * 1.5) + floor(Std. Strength * 0.5)\n```\n\n**Max Energy (%)**\n```\n100 + floor(Std. Intelligence * 0.6) + floor(Std. Wisdom * 0.6) + floor(Std. Faith * 0.6) + floor(Std. Constitution * 0.2)\n```",

    "KeyFormulasCombatStatsTitle": "Combat Bonuses",
    "KeyFormulasCombatStatsDesc": "These bonuses are calculated based on your **modified** (including gear and effects) characteristics and directly impact your combat effectiveness.",
    "KeyFormulasCombatStatsContent": "**Characteristic Damage Bonus (%)**\n```\nfloor(Modified Characteristic / 2.5)\n```\n\n**Crit Damage Multiplier**\n```\n1.5 + (floor(Modified Luck / 2) / 100)\n```",
    
    "KeyFormulasActionChecksTitle": "Action Checks",
    "KeyFormulasActionChecksDesc": "This formula is the basis for determining the outcome of any action with an uncertain result.",
    "KeyFormulasActionChecksContent": "The outcome of most actions is determined by comparing your roll against the difficulty.\n```\nFinal Difference = (Your d20 + Stat Modifier) - (AI's d20 + Difficulty Modifier)\n```\nThe higher the positive difference, the more successful the action.",
    
    "KeyFormulasSkillScalingTitle": "Skill Scaling",
    "KeyFormulasSkillScalingDesc": "The power of your skills is not static; it grows with your level, characteristics, and mastery.",
    "KeyFormulasSkillScalingContent": "The effectiveness of your skills grows with you. This is the primary way your power increases.\n```\nFinal Effect = Base Effect * (1 + Char Bonus% + Level Bonus% + Mastery Bonus%)\n```",
    
    "KeyFormulasXPTitle": "Experience Gain",
    "KeyFormulasXPDesc": "Experience is awarded for successful actions, completing quests, and creative solutions. The amount depends on the difficulty, risk, and impact of your actions on the world.",
    "KeyFormulasXPContent": "Experience is calculated based on multiple factors, including the complexity and creativity of your approach.\n```\nXP = floor((BaseXP + CreativityBonus + RiskBonus) * ImpactMultiplier * LevelScaling)\n```"
  },
  ru: {
    // Help Guide
    "HelpGuideTitle": "Руководство по игре",
    "CharacteristicChecksTitle": "Проверки Характеристик",
    "CharacteristicChecksFullDesc": "Каждое ваше действие, исход которого не предопределен, требует **Проверки Характеристики**. Это ключевая механика, которая определяет, насколько успешно вы справились с поставленной задачей, будь то взлом замка, убеждение стражника или атака на врага.\n\nВсякий раз, когда вы совершаете такое действие, за кулисами происходит следующий процесс:\n\n* **1. Ассоциация с характеристикой:** Мастер Игры (ИИ) определяет, какая из ваших характеристик (Сила, Ловкость, Интеллект и т.д.) является ключевой для этого действия.\n* **2. Бросок кости (d20):** Система бросает 20-гранную кость. На результат могут повлиять **Преимущество** или **Помеха**, которые разделяются на два уровня:\n    *   **Обычное Преимущество/Помеха:** Бросаются две 20-гранные кости, и для проверки используется **лучший** (при Преимуществе) или **худший** (при Помехе) результат.\n    *   **Великое Преимущество / Ужасная Помеха:** Бросаются три 20-гранные кости, и для проверки используется **лучший** (при Преимуществе) или **худший** (при Помехе) результат из трех.\n\n    Эти условия применяются в зависимости от обстоятельств (например, атака из засады дает Преимущество, а стрельба в темноте — Помеху).\n* **3. Расчет модификаторов:** К вашему броску добавляется **Модификатор Статистики** (рассчитывается из вашей характеристики и уровня), а против вас выступает **Модификатор Сложности** (зависит от сложности задачи, ситуации и броска кости Мастера Игры).\n* **4. Определение результата:** Итоговая разница между вашим результатом и сложностью определяет степень успеха. Существует шесть уровней исхода:\n    *   **Критический Успех:** Вы достигаете цели с блеском, превосходя все ожидания. Вы не только добиваетесь своего, но и получаете дополнительный бонус или создаете неожиданное преимущество.\n    *   **Полный Успех:** Вы полностью и без каких-либо негативных последствий достигаете своей цели.\n    *   **Частичный Успех:** Вы достигаете основной цели, но с ценой: возникают осложнения, результат оказывается неполным или появляются непредвиденные побочные эффекты.\n    *   **Незначительная Неудача:** Вы не достигаете своей цели. Последствия минимальны — возможно, вы зря потратили время или оказались в слегка невыгодном положении.\n    *   **Серьезная Неудача:** Вы проваливаетесь, и ситуация заметно ухудшается. Вы можете получить урон, потерять предмет или дать врагу значительное преимущество.\n    *   **Критическая Неудача:** Катастрофический провал. Происходит наихудший из возможных сценариев с тяжелыми и, возможно, долгосрочными последствиями.",

    "Critical Success": "Критический Успех",
    "Full Success": "Полный Успех",
    "Partial Success": "Частичный Успех",
    "Minor Failure": "Незначительная Неудача",
    "Serious Failure": "Серьезная Неудача",
    "Critical Failure": "Критическая Неудача",

    "CharacteristicChecksExampleTitle": "Детальный Пример: Убеждение Стражника",
    "CharacteristicChecksExampleScenario": "Вы пытаетесь убедить строгого на вид стражника пропустить вас через городские ворота после наступления комендантского часа. Это рискованно, и стражник выглядит неподкупным.",
    "CharacteristicChecksExampleContent": "**1. Ассоциация с Характеристикой:** Мастер Игры определяет, что для убеждения стражника ключевой является характеристика **Убеждение**.\n\n**2. Преимущество/Помеха:** У вас нет явных преимуществ, но вы пытаетесь действовать ночью, что вызывает подозрения. Мастер Игры решает, что у вас **Обычная Помеха**.\n\n**3. Бросок Костей:** Из-за Помехи система бросает две кости d20 и берет худший результат. Допустим, выпало **16** и **7**. Для проверки используется **7**.\n\n**4. Расчет Модификаторов:**\n*   **Ваш Модификатор Статистики:** Рассчитывается из вашей характеристики Убеждения (40) и уровня (10). Допустим, итоговый модификатор равен **+32**.\n*   **Модификатор Сложности:** Рассчитывается из сложности задачи (стражник неподкупен), ситуации (ночь) и броска кости Мастера Игры. Допустим, бросок ИИ был **12**, а итоговый модификатор сложности — **+25**.\n\n**5. Итоговая Разница и Результат:**\n*   **Ваш Итог:** 7 (бросок) + 32 (модификатор) = **39**\n*   **Итог Сложности:** 12 (бросок ИИ) + 25 (модификатор) = **37**\n*   **Разница:** 39 - 37 = **+2**\n*   **Результат:** Разница +2 попадает в диапазон от 0 до 5. Это **Частичный Успех**.\n\n**Заключение:** Вы не смогли полностью убедить стражника, но он не поднял тревогу. Он говорит: «Я не могу вас пропустить через главные ворота, но если вы поторопитесь, то сможете проскользнуть через старый пролом в стене к востоку отсюда. И чтобы я вас больше не видел». Вы достигли цели (пройти в город), но с осложнением (пришлось использовать небезопасный путь и привлечь к себе внимание).",

    "CombatTitle": "Бой",
    "CombatFullDesc": "Бой — это структурированный процесс, который проходит в **раундах**. В каждом раунде все участники совершают свой ход в порядке **Инициативы**, которая определяется вашей характеристикой **Скорость**.\n\nКлючевые концепции:\n\n* **1. Единицы Процентов vs. Проценты:** Это важно! Здоровье и урон измеряются в **Единицах Процентов (%)** — это абсолютное значение (мощный босс может иметь '500%' здоровья). Сопротивления измеряются в обычных **Процентах (%)** и используются для расчета снижения урона.\n* **2. Действия в ход:** В свой ход вы можете совершить одно **Основное Действие** (атака, использование навыка) и **Перемещение**.\n* **3. Атака и Урон:** Ваша атака — это **Проверка Характеристики**. В случае успеха вы наносите урон, который вычитается из здоровья цели. Урон зависит от вашего оружия, навыков и характеристик.\n* **4. Раны:** Получение значительного урона (более 25% от максимального здоровья за один раз) может привести к **Ранам** — серьезным травмам, которые накладывают постоянные ослабления, пока не будут вылечены специальными средствами или отдыхом.\n* **5. Эффекты:** Многие навыки и атаки накладывают временные эффекты:\n    *   **Усиления (Баффы):** Положительные эффекты, увеличивающие ваши характеристики или урон.\n    *   **Ослабления (Дебаффы):** Отрицательные эффекты, снижающие характеристики противника.\n    *   **Урон со временем (DoT):** Урон, наносимый каждый ход (яд, горение).\n    *   **Контроль:** Эффекты, ограничивающие действия цели (оглушение, обездвиживание).",

    "StealthAndDetectionTitle": "Скрытность и Обнаружение",
    "StealthAndDetectionFullDesc": "Скрытность - это активное состояние, позволяющее вам избегать врагов и получать тактическое преимущество. Это не просто невидимость, а постоянное соревнование между вашей незаметностью и бдительностью противников.\n\n* **1. Вход в скрытность:** Чтобы стать скрытным, вы должны заявить о своем намерении (например, «Я пытаюсь красться»). Мастер Игры определит, возможно ли это в текущей обстановке. Если да, вы пройдете проверку **Ловкости**. Успех означает, что вы вошли в режим скрытности.\n* **2. Уровень обнаружения:** Ваша незаметность измеряется **Уровнем обнаружения** (от 0 до 100). 0 — вы полностью скрыты. 100 — вас обнаружили. Чем выше уровень, тем больше подозрений вы вызываете.\n* **3. Действия в скрытности:** Любые ваши действия (передвижение, взлом замка, открытие двери) увеличивают ваш Уровень обнаружения. Шумные действия, такие как бег в тяжелой броне или громкий разговор, немедленно выводят вас из скрытности.\n* **4. Обнаружение:** Враги могут вас заметить. Если ваш Уровень обнаружения становится достаточно высоким, они начнут активно вас искать, совершая проверки **Восприятия** против вашей скрытности. Успех с их стороны может либо еще больше повысить ваш уровень обнаружения, либо полностью вас раскрыть.\n* **5. Преимущества скрытности:** Атака из скрытности на ничего не подозревающего врага дает вам **Великое Преимущество** при броске на атаку, что значительно повышает ваши шансы на критический удар. После атаки вы выходите из скрытности.",
    
    "LootGenerationTitle": "Генерация Добычи (Лута)",
    "LootGenerationFullDesc": "Система создания предметов в игре — это не просто случайность. Это сложный процесс, который учитывает вашего персонажа, его снаряжение и текущую ситуацию, чтобы создавать уникальные и подходящие награды. Процесс состоит из двух этапов: сначала система генерирует **Шаблон Лута** — своего рода «рецепт», а затем Мастер Игры (ИИ) превращает этот шаблон в полноценный предмет с названием и историей.",
    "LootGenerationKeyFactorsTitle": "Ключевые Факторы (Коэффициенты)",
    "LootGenerationKeyFactorsDesc": "В конце каждого вашего хода Мастер Игры оценивает ситуацию по пяти ключевым коэффициентам. Эти коэффициенты напрямую влияют на качество добычи в следующем ходу:",
    "LootGenerationKeyFactorsL1": "**Коэффициент Поиска Предметов:** Насколько ваше текущее снаряжение помогает в поиске сокровищ.",
    "LootGenerationKeyFactorsL2": "**Коэффициент Локации:** Насколько богата или опасна текущая локация.",
    "LootGenerationKeyFactorsL3": "**Коэффициент Опасности:** Насколько напряженная ситуация в данный момент. Больше опасность — выше награда.",
    "LootGenerationKeyFactorsL4": "**Коэффициент Логики:** Насколько логично найти что-то ценное именно здесь и сейчас.",
    "LootGenerationKeyFactorsL5": "**Коэффициент Персонажей:** Учитывает сложность социального взаимодействия (влияет в меньшей степени).",
    "LootGenerationPlayerInfluenceTitle": "Ваше Влияние",
    "LootGenerationPlayerInfluenceDesc": "Помимо внешних факторов, ваш персонаж — главный катализатор хорошей добычи:",
    "LootGenerationPlayerInfluenceL1": "**Удача:** Возможно, самая важная характеристика для поиска сокровищ. Она значительно повышает общее качество добычи и дает шанс на **«Удар Удачи»** — специальное событие, которое может улучшить качество предмета на целый уровень или добавить ему дополнительный бонус!",
    "LootGenerationPlayerInfluenceL2": "**Уровень:** Чем выше ваш уровень, тем выше потенциал для нахождения предметов более высокого качества.",
    "LootGenerationProcessTitle": "Процесс Генерации Шаблона",
    "LootGenerationProcessDesc": "Для каждого потенциального предмета система проходит следующие этапы:",
    "LootGenerationProcessL1": "**1. Будет ли что-то найдено?** Всегда есть шанс ничего не найти, но ваши множители и удача могут свести его к минимуму.",
    "LootGenerationProcessL2": "**2. Определение Качества:** Система совершает «бросок», чтобы определить качество предмета (от Уникального до Мусора). Ваши множители, уровень и удача сдвигают вероятности в вашу пользу, увеличивая шансы на получение редких вещей.",
    "LootGenerationProcessL3": "**3. Генерация Бонусов:** Качество предмета определяет, сколько бонусов он получит. У предметов высокого качества гораздо выше шанс получить **«особый» бонус** — уникальный эффект, проклятие или мощное условное усиление, а не просто прибавку к характеристике.",
    "LootGenerationFinalResultTitle": "Итоговый Результат",
    "LootGenerationFinalResultDesc": "В результате этого процесса создается **Шаблон Лута**, который передается Мастеру Игры. Именно поэтому два одинаковых по названию меча могут иметь совершенно разные свойства — они были созданы по разным шаблонам, сгенерированным в уникальных для вас обстоятельствах.",

    "KeyFormulasTitle": "Ключевые формулы",
    "KeyFormulasDesc": "Понимание этих формул поможет вам принимать более взвешенные решения при развитии персонажа и в бою.",
    "KeyFormulasPrimaryStatsTitle": "Основные параметры",
    "KeyFormulasPrimaryStatsDesc": "Эти параметры рассчитываются на основе ваших **стандартных** (базовых) характеристик и определяют вашу выживаемость и запас сил. Бонусы от снаряжения на них не влияют.",
    "KeyFormulasPrimaryStatsContent": "**Макс. Здоровье (%)**\n```\n100 + floor(Станд. Телосложение * 1.5) + floor(Станд. Сила * 0.5)\n```\n\n**Макс. Энергия (%)**\n```\n100 + floor(Станд. Интеллект * 0.6) + floor(Станд. Мудрость * 0.6) + floor(Станд. Вера * 0.6) + floor(Станд. Телосложение * 0.2)\n```",

    "KeyFormulasCombatStatsTitle": "Боевые бонусы",
    "KeyFormulasCombatStatsDesc": "Эти бонусы рассчитываются на основе ваших **модифицированных** (с учетом снаряжения и эффектов) характеристик и напрямую влияют на вашу эффективность в бою.",
    "KeyFormulasCombatStatsContent": "**Бонус к урону от характеристики (%)**\n```\nfloor(Модиф. Характеристика / 2.5)\n```\n\n**Множитель крит. урона**\n```\n1.5 + (floor(Модиф. Удача / 2) / 100)\n```",
    
    "KeyFormulasActionChecksTitle": "Проверки действий",
    "KeyFormulasActionChecksDesc": "Эта формула является основой для определения исхода любого действия с неопределенным результатом.",
    "KeyFormulasActionChecksContent": "Исход большинства действий определяется сравнением вашего броска со сложностью.\n```\nИтоговая разница = (Ваш d20 + Модификатор Статистики) - (d20 ИИ + Модификатор Сложности)\n```\nЧем выше положительная разница, тем успешнее действие.",
    
    "KeyFormulasSkillScalingTitle": "Масштабирование навыков",
    "KeyFormulasSkillScalingDesc": "Сила ваших навыков не статична; она растет вместе с вашим уровнем, характеристиками и мастерством.",
    "KeyFormulasSkillScalingContent": "Эффективность ваших навыков растет вместе с вами. Это основной способ увеличения вашей мощи.\n```\nИтоговый эффект = Базовый эффект * (1 + Бонус Характеристики% + Бонус Уровня% + Бонус Мастерства%)\n```",
    
    "KeyFormulasXPTitle": "Получение опыта",
    "KeyFormulasXPDesc": "Опыт начисляется за успешные действия, выполнение квестов и творческие решения. Количество зависит от сложности, риска и влияния ваших действий на мир.",
    "KeyFormulasXPContent": "Опыт рассчитывается на основе множества факторов, включая сложность и креативность вашего подхода.\n```\nОпыт = floor((БазовыйОпыт + БонусКреативности + БонусРиска) * МножительВлияния * МасштабУровня)\n```"
  }
};